<MenuScreen>:
    canvas.before:
        Color:
            rgba: rgba("#ffe6f3")
        Rectangle:
            pos:self.pos
            size:self.size
    BoxLayout:
        orientation:'vertical'
        padding:'20dp'
        spacing:'20dp'
        Label:
            id: title_game
            text:'cat clicker'
            font_name:'assets/EBGaramond-VariableFont_wght.ttf'
            color: '#695E9C'
            font_size:'40sp'